lastUpdated = "2019-02-08 21:17:48"
serviceName = "my-file"
version = "5.0.10"

[[apps]]
  appName = "predix-acs-new"
  pipeline = "testFilePath2"

  [[apps.packages]]
    name = "testPackageName2"
    type = "testPackageType2"

[[apps]]
  appName = "predix-acs-n"
  pipeline = "testFilePath2"

  [[apps.packages]]
    name = "testPackageName2"
    type = "testPackageType2"
