lastUpdated = "2019-02-10 23:17:15"
serviceName = "my-file"
version = "5.0.16"

[[apps]]
  appName = "predix-acs1"
  pipeline = "access-control-service/5.0.5/Jenkinsfile_DeployPPC-5.0.5"

  [[apps.packages]]
    name = "testPackageName11"
    type = "testPackageType11"

  [[apps.packages]]
    name = "testPackageName12"
    type = "testPackageType12"

  [[apps.packages]]
    name = "testPackageName13"
    type = "testPackageType13"

[[apps]]
  appName = "predix-acs"
  pipeline = "testFilePath12"

  [[apps.packages]]
    name = "testPackageName12"
    type = "testPackageType12"
