lastUpdated = "2019-02-08 21:06:07"
serviceName = "access-control-service"
version = "5.0.6"

[[apps]]
  appName = "predix-acs"
  pipeline = "access-control-service/5.0.5/Jenkinsfile_DeployPPC-5.0.5"

  [[apps.packages]]
    name = "eshwar-acs-deploy-5.0.5-SNAPSHOT.tgz"
    type = "artifact"

  [[apps.packages]]
    name = "eshwar-service-5.0.5-SNAPSHOT.jar"
    type = "artifact"

  [[apps.packages]]
    name = "eshwar-service-5.0.5-SNAPSHOT-exec.jar"
    type = "artifact"

[[apps]]
  appName = "predix-acs"
  pipeline = "access-control-service/5.0.5/Jenkinsfile_DeployPPC-5.0.5"

  [[apps.packages]]
    name = "eshwar"
    type = "developer"
