lastUpdated = "2019-02-10 11:41:19"
serviceName = "my-file"
version = "5.0.12"

[[apps]]
  appName = "predix-acs1"
  pipeline = "access-control-service/5.0.5/Jenkinsfile_DeployPPC-5.0.5"

  [[apps.packages]]
    name = "testPackageName6"
    type = "testPackageType6"

  [[apps.packages]]
    name = "testPackageName7"
    type = "testPackageType7"

  [[apps.packages]]
    name = "testPackageName8"
    type = "testPackageType8"
