serviceName = "my-file"
version = "5.0.5"
lastUpdated = "2019-02-04 19:12:32"
__timeStamp = 0

[[apps]]
  appName = "predix-acs"
  pipeline = "access-control-service/5.0.5/Jenkinsfile_DeployPPC-5.0.5"
  __timeStamp = 0

    [[apps.packages]]
      name = "eshwar-acs-deploy-5.0.5-SNAPSHOT.tgz"
      type = "artifact"
      __timeStamp = 0

    [[apps.packages]]
      name = "eshwar-service-5.0.5-SNAPSHOT.jar"
      type = "artifact"
      __timeStamp = 0

    [[apps.packages]]
      name = "eshwar-service-5.0.5-SNAPSHOT-exec.jar"
      type = "artifact"
      __timeStamp = 0
