lastUpdated = "2019-02-11 09:55:45"
serviceName = "my-file"
version = "5.0.1"

[[apps]]
  appName = "predix-acs"
  pipeline = "access-control-service/5.0.5/Jenkinsfile_DeployPPC-5.0.5"

  [[apps.packages]]
    name = "testPackageName11"
    type = "testPackageType11"

  [[apps.packages]]
    name = "testPackageName12"
    type = "testPackageType12"
