lastUpdated = "2019-02-10 20:17:31"
serviceName = "my-file"
version = "5.0.14"

[[apps]]
  appName = "predix-acs1"
  pipeline = "access-control-service/5.0.5/Jenkinsfile_DeployPPC-5.0.5"

  [[apps.packages]]
    name = "testPackageName6"
    type = "testPackageType6"

  [[apps.packages]]
    name = "testPackageName7"
    type = "testPackageType7"

  [[apps.packages]]
    name = "testPackageName8"
    type = "testPackageType8"

  [[apps.packages]]
    name = "testPackageName9"
    type = "testPackageType9"

[[apps]]
  appName = "predix-acs"
  pipeline = "testFilePath9"

  [[apps.packages]]
    name = "testPackageName9"
    type = "testPackageType9"
