lastUpdated = "2019-02-10 20:21:19"
serviceName = "my-file"
version = "5.0.15"

[[apps]]
  appName = "predix-acs1"
  pipeline = "testFilePath11"

  [[apps.packages]]
    name = "testPackageName11"
    type = "testPackageType11"
